package org.example;

public enum JobTitle {
    SOFTWARE_DEVELOPER,
    SYSTEM_ADMINISTRATOR,
    QA_ENGINEER,
    DATA_ANALYST,
    INFORMATION_SECURITY_ENGINEER,
    DATABASE_ADMINISTRATOR,
    WEB_DEVELOPER,
    SYSTEMS_ARCHITECT,
    BUSINESS_ANALYST,
    NETWORK_ADMINISTRATOR,
    SERVER_ADMINISTRATOR,
    DATA_ARCHITECT,
    MACHINE_LEARNING_ENGINEER,
    SYSTEMS_ANALYST,
    SYSTEM_INTEGRATOR,
    CLOUD_ADMINISTRATOR,
    CLOUD_SOLUTIONS_ARCHITECT
}
